django/week4/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include

from . import views

urlpatterns = [
	path(r'', views.home, name='home'),
	path(r'portfolio', views.portfolio, name='portfolio'),
	path(r'contact', views.contact, name='contact'),
    path(r'resume', include('resume.urls', namespace='resume')),
    path('admin/', admin.site.urls),
]

django/week4/resume/urls.py
from django.urls import path

from . import views

app_name="resume"

urlpatterns = [
   path(r'', views.home, name='home'),
]

django/week4/resume/models.py
from django.db import models

# Create your models here.

class Experience(models.Model):
    parent_resume = models.ForeignKey('Resume',on_delete=models.CASCADE, default=1)
    title = models.CharField(max_length=100,null=False, blank=False)
    location = models.CharField(max_length=100,null=False, blank=False)
    start_date = models.DateField(null=False, blank=False)
    end_date = models.DateField(null=False, blank=False)
    description = models.TextField()

    def __str__(self):
        return self.title

class Education(models.Model):
    parent_resume = models.ForeignKey('Resume',on_delete=models.CASCADE, default=1)
    institution_name = models.CharField(max_length=100,null=False, blank=False)
    location = models.CharField(max_length=100,null=False, blank=False)
    degree = models.CharField(max_length=20,null=False, blank=False)
    major = models.CharField(max_length=100,null=False, blank=False)
    gpa = models.FloatField(null=False, blank=False)

    def __str__(self):
        return self.degree

class Resume(models.Model):
    First_name = models.CharField(max_length=40,null=False,blank=False)
    Last_name = models.CharField(max_length=40,null=False,blank=False)

    def __str__(self):
       return self.Last_name

    def get_full_name(self):
        """
        should return full name"
        """
        return"{} {}".format(self.First_name, self.Last_name)

    def get_last_name_first_name(self):
        """
        should return last name then first name
        """
        return"{} {}".format(self.Last_name, self.First_name)
    def get_experience(self):
        """
        return all foreign key related Experience objects
        """
        return self.experience_set.all()
    def get_education(self):
        """
        return all foreign key related Education objects
        """
        return self.education_set.all()

django/week4/portfolio/views.py
from django.shortcuts import render

def home(request):
	'''
	Renders home page
	'''
	context = {}
	return render(request,'home.html',context)

def portfolio(request):
	'''
	Renders portfolio page
	'''
	context = {}
	return render(request,'portfolio.html',context)

def contact(request):
	'''
	Renders contact page
	'''
	context = {}
	return render(request,'contact.html',context)

django/week4/resume/views.py
from django.shortcuts import render
from .models import Education, Experience, Resume
# Create your views here.

def home(request):
    """
    renders the resume home template
    """ 
    address = "400 Commercial Street, Manchester, NH, 03101"
    phone = "(603) 289-0134"
    email = "odo1001@wildcats.unh.edu"
    skills = ["Django","Python"]
    context = {}
    first_resume = Resume.objects.first()
    experiences = Experience.objects.order_by('title')
    context = {'my_addr':address,'my_phone':phone,"my_email":email,
    'my_skills':skills,'my_res':first_resume}
    return render(request,'resume/home.html',context)

django/week4/resume/templates/resume/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
	<h1>My Resume</h1>
	<p>Name: {{my_res.get_full_name}}</p>
	<p>Address: {{my_addr}}</p>
	<p>Phone: {{my_phone}}</p>
	<p>Email: {{my_email}}</p>
	<h2>Education</h2>
	<table class="mytb">
		<th>Institution</th>
		<th>Location</th>
		<th>Degree</th>
		<th>Major</th>
		<th>GPA</th>
		{% for education in my_res.get_education %}
		<tr>
			<td>{{education.institution_name}}</td>
			<td>{{education.location}}</td>
			<td>{{education.degree}}</td>
			<td>{{education.major}}</td>
			<td>{{education.gpa}}</td>
		</tr>
		{% endfor %}
	</table>
	<h2>Experience</h2>
	<table class="mytb">
		<th>Title</th>
		<th>Job Title</th>
		<th>Job Functions</th>
		<th>From - End</th>
		<th>Description</th>
		{% for experience in my_res.get_experience %}
		<tr>
			<td>{{experience.title}}</td>
			<td>{{experience.location}}</td>
			<td>{{experience.start_date}}</td>
			<td>{{experience.end_date}}</td>
			<td>{{experience.description}}</td>
		</tr>
		{% endfor %}
	</table>
	<h2>Skills</h2>
	{% for skills in my_skills %}
		<ul>
			<li>{{skills}}</li>
		</ul>

	{% endfor %}
{% endblock %}

django/week4/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <title>Portfolio</title>
    <link rel='stylesheet' href="{% static 'css/style.css' %}" />
  </head>
  <body>
      <nav>
        <a href="{% url 'home' %}">Home</a> |
        <a href="{% url 'resume:home' %}">Resume</a> |
        <a href="{% url 'portfolio' %}">Portfolio</a> |
        <a href="{% url 'contact' %}">Contact</a>
      </nav>

      {% block content %}
      {% endblock %}

  </body>
</html>

django/week4/templates/contact.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
    <h1>Contact Me!</h1>
    <form>
        <div>
            Full name:<br>
            <input type="text" name="fullname" placeholder="e.g. John Doe">
        </div>
        <div>
            E-mail:<br>
            <input type="email" name="email" placeholder="e.g. johndoe@mail.com">
        </div>
        <div>
            Reason for contacting:<br>
             <textarea name="contactreason" rows="15" cols="40"></textarea>
        </div>
        <input type="submit" value="Submit!">
    </form> 
{% endblock %}

django/week4/templates/home.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
    <h1>Welcome to Oreva's Portfolio</h1>
    <h4>...something to intrigue you!</h4>
{% endblock %}

django/week4/templates/portfolio.html
{% extends 'base.html' %}
<!DOCTYPE html>
{% load static %}
{% block content %}
    <h1>My Portfolio</h1>
    <ol>
        <li>    
            <a href="https://github.com/Revodavid1/comp830project">Lost in Pandora Game</a>
            <p>Desc: A text adeventure game built with java.</p>
        </li>
        <li>
            <a href="https://github.com/Revodavid1/bitquiz">BitQuiz</a>
            <p>Desc: A multiple choice exam platform built with PHP and JavaScript.</p>
        </li>
    </ol>
{% endblock %}