python/django/djangocc/djangocc/urls.py
from django.contrib import admin
from django.urls import path,include

from . import views



urlpatterns = [
    path(r'', views.home, name='home'),
    path(r'flashcards', include('flashcards.urls',namespace='flashcards')),
    path(r'admin/', admin.site.urls),
]

python/django/djangocc/flashcards/urls.py
#flachcards url
from django.urls import path

from . import views

app_name="flashcards"

urlpatterns = [
    path(r'', views.home, name='home'),
]

python/django/djangocc/flashcards/models.py
from django.db import models

# Create your models here.
class Deck(models.Model):
    title = models.CharField(max_length=64,null=False, blank=False)
    description = models.CharField(max_length=255, null=False, blank=True)

    def __str__(self):
        return self.title

class Card(models.Model):
    parentDeck = models.ForeignKey(Deck, on_delete=models.CASCADE)
    front = models.TextField()
    back = models.TextField()

    def __str__(self):
       return self.front

    def has_prev_card(self):
        '''
        Returns true if the card is not the first card
        in the deck.
        '''
        first_card_in_deck = self.parentDeck.card_set.first()
        if self == first_card_in_deck:
            return False
        return True

    def get_prev_card(self):
        '''
        Returns previous card in deck
        '''
        return self.parentDeck.card_set.filter(id__lt=self.id).last()

    def has_next_card(self):
        '''
        Returns true if the card is not the last card
        in the deck
        '''
        last_card_in_deck = self.parentDeck.card_set.last()
        if self == last_card_in_deck:
            return False
        return True

    def get_next_card(self):
        '''
        Returns next card in deck
        '''
        return self.parentDeck.card_set.filter(id__gt=self.id).first()

python/django/djangocc/djangocc/views.py
from django.shortcuts import render

def home(request):
	'''
	Renders home page
	'''
	
	
	context = {}
	return render(request,'home.html',context)

python/django/djangocc/flashcards/views.py
from django.shortcuts import render
from .models import Deck
# Create your views here.

def home(request):
	"""
	renders the flashcard ome template
	"""	
	qs = Deck.objects.order_by('-title')
	context = {'decks':qs}
	return render(request,'flashcards/home.html',context)

python/django/djangocc/flashcards/templates/flashcards/home.html
{% extends 'base.html' %}
{% block content %}
		{% if decks %}
			<ul>
				{% for deck in decks %}
					<li>{{deck.title}}</li>
				{% endfor %}
			</ul>
		{% else %}
			<h1>No Decks Found, Contact Admin!</h1>
		{% endif %}
{% endblock %}
	

python/django/djangocc/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
	<head>
		<title>uStudy</title>
		<link rel='stylesheet' href="{% static 'css/style.css' %}" />
	</head>
	<body>
		
			<nav>
				<a href="{% url 'home' %}">uStudy</a> |
				<a href="{% url 'flashcards:home' %}">Decks</a> |
				<a href="">About</a> |
				<a href="">Contacts</a> |
			</nav>
			
			{% block content %}

			{% endblock %}
	</body>
</html>

python/django/djangocc/templates/home.html
{% extends 'base.html' %}
{% block content %}
		<div class="homepage-content">
			<div class="homepage-banner">
				<h1>uStudy</h1>
				<hr>
				<h4>Harness the power of U!</h4>
				<a class="button" href="">Get Started</a>
			</div>
		</div>
{% endblock %}